version: '2'
services:
  openldap:
    image: leejoneshane/tpedusso:openldap
    container_name: openldap
    hostname: ldap
    restart: always
    
  ldapadmin:
    image: leejoneshane/tpedusso:phpldapadmin
    container_name: ldapadmin
    restart: always
    ports:
      - "8080:80"
    links:
      - openldap:openldap
    
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: dbpassword
    restart: always
    
  redis:
    image: redis
    container_name: redis
    restart: always
    
  laravel:
    image: leejoneshane/tpedusso
    container_name: laravel
    volumes:
      - ./htdocs:/var/www/localhost/htdocs
    environment:
      APP_DEBUG: 'true'
      APP_KEY: 'base64:fx/bpfXs+pQ3j7eeZP5gkqWxBtbhUpaqELdpQeeP/N8='
      DOMAIN: ldap.tp.edu.tw
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      SESSION_CONNECTION: session
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: dbpassword
      LDAP_HOST: ldap://openldap
      LDAP_ROOTDN: cn=admin,dc=tp,dc=edu,dc=tw
      LDAP_ROOTPWD: test
      MAIL_DRIVER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: your@gmail.com
      MAIL_PASSWORD: password
      MAIL_ENCRYPTION: tls
      SAML_MAIL: ms.tp.edu.tw
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql:mysql
      - redis:redis
    restart: always
